import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'
import {useState, useEffect} from 'react'
import Input from './Components/Input'

export default function Chat() {

  const [userName, setUserName] = useState('')
  const [messageText, setMessageText] = useState<string>('')
  const [messages, setMessages] = useState<string[]>([])
  const [isUserNameSubmitted, setIsUserNameSubmitted] = useState(false);

  useEffect(()=>{
    if (sessionStorage.getItem("userName")){
      setIsUserNameSubmitted(true);
      let userName = sessionStorage.getItem("userName")
      if (typeof userName === "string"){
        setUserName(userName)
      }
    }
  }, []);
  function inputNameHandler(value: string){
    setUserName(value);
  }
  function submitNameHandler(e: React.FormEvent<HTMLFormElement>){
    e.preventDefault();
    if (userName!==''){
      sessionStorage.setItem("userName", userName);
      setIsUserNameSubmitted(true);
    }
  }
  function inputMessageHandler(value: string){
    setMessageText(value)
  }
  function submitMessageHandler(e: React.FormEvent<HTMLFormElement>){
    e.preventDefault();
    setMessages(current => [...current, messageText])
    localStorage.setItem('messages', JSON.stringify(messages));
  }
  const firstRender= () =>{
    if (!isUserNameSubmitted){
      return (
        <div className="row mt-3">
          <div className="col-lg-4 offset-lg-4 col-sm-6 offset-sm-3">
          <Input submitHandler={(e: React.FormEvent<HTMLFormElement>)=>submitNameHandler(e)} inputHandler={(value: string)=>inputNameHandler(value)} value={userName} target={'authorization'} />
          </div>
        </div>
      )
    }
    return (
      <div className="d-flex flex-column-reverse" style={{height: '80vh'}}>
        <Input submitHandler={(e: React.FormEvent<HTMLFormElement>)=>submitMessageHandler(e)} inputHandler={(value: string)=>inputMessageHandler(value)} value={messageText} target={'message'} />
      </div>
    )
  }
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Lonely chat</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossOrigin="anonymous" />
        <script defer src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossOrigin="anonymous"></script>
      </Head>
      <div className='container'>
        <div className='row justify-content-center mt-3'>
          <div className="col-6 col-xs-12 h3 text-center">Lonely chat</div>  
        </div>
        {firstRender()}
      </div>
    </div>
  )
}
